
# Pando configuration for privatenet
genesis:
  hash: ""
p2p:
  port: 12000
   seeds:
  seedPeerOnlyOutbound: true
  address: 127.0.0.1
log:
  levels: "*:info,guardian:debug"
storage:
  statePruningRetainedBlocks: 2048
rpc:
  enabled: true